version: '3.9'

services:

  infra-agent:
    container_name: newrelic-infra
    environment:
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=cruddb
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./postgres-config.yml:/etc/newrelic-infra/integrations.d/postgres-config.yml
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: localhost:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cruddb

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prom-config.yml:/etc/prometheus/prometheus.yml

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter
    depends_on:
      - postgres
      - prometheus
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_URI: localhost:5432/cruddb?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgres


volumes:
  postgres_data: